import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { SignInFirebase, SignUpFirebase } from "@/services/firebase";

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");


  return (
    <>
      <Head>
        <title>Firebase Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <div className="cardSignUp">
        <h1>Sign Up</h1>
        <form onSubmit={() => SignUpFirebase(email,password)}>
          <input
            type="email"
            placeholder="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type="password"
            placeholder="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button type="submit">Sign Up</button>
        </form>
        </div>
      </main>
    </>
  );
}